spring:
  application:
    name: corki
  boot:
    admin:
      client:
        url: http://127.0.0.1:8085

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info

